name: Build & Publish to GH Pages
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Anaconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          miniconda-version: 'latest'
          python-version: 3.8
          environment-file: environment.yml
          activate-environment: pyecon
      - name: Display Conda Environment Versions
        shell: bash -l {0}
        run: conda list
      - name: Display Pip Versions
        shell: bash -l {0}
        run: pip list
      - name: Build HTML
        shell: bash -l {0}
        run: |
          jb build lectures --path-output ./
      - name: Build Download Notebooks (sphinx-tojupyter)
        shell: bash -l {0}
        run: |
          jb build lectures --path-output ./ --builder=custom --custom-builder=jupyter
      - name: Copy Download Notebooks for GH-PAGES
        shell: bash -l {0}
        run: |
          mkdir _build/html/_notebooks
          cp _build/jupyter/*.ipynb _build/html/_notebooks
      - name: Deploy website to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html/
      - name: Upload "_build" folder (cache)
        uses: actions/upload-artifact@v2
        with:
          name: build-cache
          path: _build
